"""Generate a torrc from an unpacked Tor Expert Bundle (uses the bundle's own, current
default bridge lines from pluggable_transports/pt_config.json)."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

EXE = ".exe" if os.name == "nt" else ""


class TorConfigError(Exception):
    pass


def _find(bundle: Path, name: str) -> Path | None:
    hits = sorted(bundle.rglob(name), key=lambda p: len(p.parts))
    return hits[0] if hits else None


def _plain(p: Path) -> str:
    s = str(p.resolve())  # native separators: Tor on Windows treats C:/x as relative
    if any(c.isspace() for c in s) or not s.isascii():
        raise TorConfigError(
            f"path '{s}' contains spaces or non-ASCII characters, which torrc cannot express here. "
            "Move the Tor bundle / data directory to a simple path such as C:/tor")
    return s


def build_torrc(
    bundle: Path,
    data_dir: Path,
    *,
    bridges: str = "snowflake",
    bridge_lines: list[str] | None = None,
    via_socks: str | None = None,
    socks_port: int = 9050,
    control_port: int = 9051,
) -> str:
    bundle = Path(bundle)
    if not bundle.is_dir():
        raise TorConfigError(f"bundle directory not found: {bundle}")
    pt_json = _find(bundle, "pt_config.json")
    lines = [
        "# Generated by `agentveil tor-config`.",
        f"SocksPort 127.0.0.1:{socks_port} IsolateSOCKSAuth",
        f"ControlPort 127.0.0.1:{control_port}",
        "CookieAuthentication 1",
        f"DataDirectory {_plain(Path(data_dir))}",
        "ClientOnly 1",
        "AvoidDiskWrites 1",
    ]
    for geo, opt in (("geoip", "GeoIPFile"), ("geoip6", "GeoIPv6File")):
        f = _find(bundle, geo)
        if f and f.is_file():
            lines.append(f"{opt} {_plain(f)}")
    if via_socks:
        host, _, port = via_socks.rpartition(":")
        if not host or not port.isdigit():
            raise TorConfigError("--via-socks must look like 127.0.0.1:1080")
        lines += ["# Tor over your own tunnel: the proxy only sees Tor traffic.",
                  f"Socks5Proxy {host}:{port}"]

    chosen: list[str] = [ln.strip() for ln in (bridge_lines or []) if ln.strip() and not ln.strip().startswith("#")]
    chosen = [ln[len("Bridge "):] if ln.startswith("Bridge ") else ln for ln in chosen]
    if not chosen and bridges != "none":
        if not pt_json:
            raise TorConfigError("pt_config.json not found in the bundle; pass --bridge-line instead")
        cfg = json.loads(pt_json.read_text(encoding="utf-8"))
        table = cfg.get("bridges", {})
        key = next((k for k in table if k == bridges or k.startswith(bridges)), None)
        if key is None:
            raise TorConfigError(f"no built-in '{bridges}' bridges; available: {', '.join(table) or 'none'}")
        chosen = list(table[key])
    if chosen:
        if not pt_json:
            raise TorConfigError("bridges need pluggable transports, but pt_config.json was not found in the bundle")
        if via_socks and any(ln.split()[0] == "snowflake" for ln in chosen):
            raise TorConfigError("snowflake cannot run through --via-socks; use webtunnel/obfs4/meek or no bridges")
        cfg = json.loads(pt_json.read_text(encoding="utf-8"))
        pt_dir = _plain(pt_json.parent) + os.sep
        needed = {ln.split()[0] for ln in chosen}
        lines.append("UseBridges 1")
        for plugin_line in cfg.get("pluggableTransports", {}).values():
            line = plugin_line.replace("${pt_path}", pt_dir).replace("${pt_extension}", EXE)
            parts = line.split()
            if len(parts) < 4 or parts[0] != "ClientTransportPlugin":
                continue
            transports = set(parts[1].split(","))
            if transports & needed:
                exe = Path(parts[3])
                if EXE and not exe.suffix and Path(str(exe) + EXE).exists():
                    parts[3] = str(exe) + EXE
                lines.append(" ".join(parts))
                needed -= transports
        if needed:
            raise TorConfigError(f"no pluggable transport binary in the bundle for: {', '.join(sorted(needed))}")
        lines += [f"Bridge {ln}" for ln in chosen]
    return "\n".join(lines) + "\n"


def tor_executable(bundle: Path) -> Path | None:
    return _find(Path(bundle), "tor" + EXE)


if __name__ == "__main__":  # pragma: no cover
    sys.stdout.write(build_torrc(Path(sys.argv[1]), Path.home() / ".agentveil" / "tor-data"))
